name: ci

env:
    HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
    - "**/CMakeLists.txt"
    - "**.cmake"
    - "**.c"
    - ".github/workflows/ci.yml"

jobs:

  core:
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: "install ARM GCC cross compiler"
      run: bash scripts/install_cross_compiler.sh

    - name: "CMake configure"
      run: cmake -B build

    - name: "CMake build"
      run: cmake --build build --parallel
